# Docker Compose override for local development
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
#
# This file overrides the server service to build locally instead of using
# the pre-built image from GitHub Container Registry. Use this for:
# - Active development and testing
# - When you need to test local code changes quickly
# - Before pushing changes that will trigger a new image build

services:
  server:
    # Override to build locally for development
    build:
      context: .
      dockerfile: Dockerfile
    
    # Development-specific environment overrides
    environment:
      - RUST_LOG=${RUST_LOG:-debug}  # More verbose logging for development
      
    # Optional: Mount source code for hot reloading (if supported)
    # volumes:
    #   - ./db/src:/app/db/src:ro
    #   - ./lib/src:/app/lib/src:ro