services:
  postgres:
    image: postgres:15
    container_name: arithmetic_postgres
    environment:
      POSTGRES_DB: arithmetic_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    # Production: Use pre-built image from GitHub Container Registry
    image: ghcr.io/ardaglobal/demo-vapp:latest
    
    # Local Development: Uncomment the lines below and comment out the 'image' line above
    # to build locally for faster iteration during development:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    
    container_name: arithmetic_server
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/arithmetic_db
      - RUST_LOG=info
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: