[package]
edition = "2021"
license = "MIT"
name    = "arithmetic-db"
version = "0.1.0"


[target.'cfg(target_os = "linux")'.dependencies]
io-uring = { version = "0.7.2", optional = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.6.0", optional = true }

[features]
default = [ "tikv-jemallocator" ]

[dependencies]
serde   = { workspace = true }
sqlx    = { workspace = true }
tokio   = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
arithmetic-lib     = { path = "../lib" }
tempfile           = "3.10"
tracing-subscriber = "0.3"
tracing-test       = "0.2"
url                = "2.5"
uuid               = { version = "1.0", features = [ "v4" ] }
