[package]
default-run = "arithmetic"
edition     = "2021"
license     = "MIT"
name        = "arithmetic-script"
version     = "0.1.0"

[[bin]]
name = "arithmetic"
path = "src/bin/main.rs"

[[bin]]
name = "evm"
path = "src/bin/evm.rs"

[[bin]]
name = "vkey"
path = "src/bin/vkey.rs"

[dependencies]
alloy-sol-types = { workspace = true }
arithmetic-db   = { path = "../db" }
arithmetic-lib  = { path = "../lib" }
clap            = { version = "4.5.42", features = ["derive", "env"] }
dotenv          = "0.15.0"
hex             = "0.4.3"
parking_lot     = { workspace = true }
qmdb            = { git = "https://github.com/ardaglobal/qmdb", package = "qmdb", branch = "mc/chore/dep-updates" }
serde           = { workspace = true, default-features = false, features = ["derive"] }
serde_json      = { version = "1.0.142", default-features = false, features = ["alloc"] }
sp1-sdk         = "5.2.1"
tracing         = "0.1.41"

[build-dependencies]
sp1-build = "5.1.0"
