[package]
default-run = "arithmetic"
edition     = "2021"
name        = "arithmetic-script"
version     = "0.1.0"

[[bin]]
name = "arithmetic"
path = "src/bin/main.rs"

[[bin]]
name = "evm"
path = "src/bin/evm.rs"

[[bin]]
name = "vkey"
path = "src/bin/vkey.rs"

[dependencies]
alloy-sol-types = { workspace = true }
arithmetic-db   = { path = "../db" }
arithmetic-lib  = { path = "../lib" }
clap            = { workspace = true, features = ["derive", "env"] }
dotenv          = { workspace = true }
hex             = { workspace = true }
serde           = { workspace = true }
serde_json      = { workspace = true }
sp1-sdk         = { workspace = true }
sqlx            = { workspace = true }
tokio           = { workspace = true }
tracing         = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }
