[package]
version = "0.1.0"
name = "fibonacci-script"
edition = "2021"
default-run = "fibonacci"

[[bin]]
name = "fibonacci"
path = "src/bin/main.rs"

[[bin]]
name = "evm"
path = "src/bin/evm.rs"

[[bin]]
name = "vkey"
path = "src/bin/vkey.rs"

[dependencies]
sp1-sdk = "5.1.0"
serde_json = { version = "1.0.142", default-features = false, features = [
	"alloc",
] }
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
clap = { version = "4.5.42", features = ["derive", "env"] }
tracing = "0.1.41"
hex = "0.4.3"
alloy-sol-types = { workspace = true }
fibonacci-lib = { path = "../lib" }
dotenv = "0.15.0"
qmdb = { git = "https://github.com/ardaglobal/qmdb", package = "qmdb", branch = "mc/chore/dep-updates" }

[build-dependencies]
sp1-build = "5.0.8"
