[profile.default]
fs_permissions = [ { access = "read-write", path = "./" } ]
libs           = [ "lib" ]
out            = "out"
src            = "src"
via_ir         = true
optimizer      = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
