[package]
edition = "2021"
license = "MIT"
name    = "arithmetic-program"
version = "0.1.0"

[dependencies]
alloy-sol-types = { workspace = true }
arithmetic-lib  = { path = "../lib" }
sp1-zkvm        = { workspace = true }
