[package]
edition = "2021"
name    = "fibonacci-program"
version = "0.1.0"

[dependencies]
alloy-sol-types = { workspace = true }
fibonacci-db    = { path = "../db" }
fibonacci-lib   = { path = "../lib" }
parking_lot     = { workspace = true }
sp1-zkvm        = "5.0.8"
